<?php
/**
 * RBAC do shell ERP prototype (*-prototype): gates de menu, módulos e ações de escrita.
 * Alinhado a config/rbac.php → menu_sidebar_gates.
 */
return [
	// RbacChecker::matchAction — UI prototype reutiliza catálogo do controller legado.
	'controller_aliases' => [
		'clientesprototype' => 'clientes',
		'produtosprototype' => 'produtos',
		'orcamentosprototype' => 'orcamentos',
		'ordensservicoprototype' => 'ordensservico',
		'servicedeskprototype' => 'servicedesk',
		'financeiroprototype' => 'financeiro',
		'bancosprototype' => 'financeirobancos',
		'fornecedoresprototype' => 'clientes',
		'pcpprototype' => 'produtos',
		'empresasprototype' => 'empresas',
		'sistemaprototype' => 'config',
		'licencasprototype' => 'licencas',
	],
	'controller_modules' => [
		'ClientesPrototype' => 'clientes',
		'ProdutosPrototype' => 'produtos',
		'OrcamentosPrototype' => 'orcamentos',
		'OrdensservicoPrototype' => 'ordensservico',
		'ServicedeskPrototype' => 'servicedesk',
		'FinanceiroPrototype' => 'financeiro',
		'BancosPrototype' => 'bancos',
		'FornecedoresPrototype' => 'fornecedores',
		'PcpPrototype' => 'pcp',
		'EmpresasPrototype' => 'empresas',
		'SistemaPrototype' => 'sistema',
		'LicencasPrototype' => 'licencas',
		'PrototypeHistory' => 'history',
	],
	'modules' => [
		'clientes' => [
			'view' => ['clientes.view', 'clientes.manage'],
			'write' => ['clientes.update', 'clientes.manage'],
		],
		'produtos' => [
			'view' => ['produtos.view', 'produtos.manage'],
			'write' => ['produtos.update', 'produtos.manage'],
			'pricing' => ['produtos.pricing', 'produtos.update', 'produtos.manage'],
		],
		'orcamentos' => [
			'view' => ['orcamentos.view', 'orcamentos.manage'],
			'write' => ['orcamentos.update', 'orcamentos.manage'],
		],
		'ordensservico' => [
			'view' => ['ordensservico.list', 'ordensservico.view', 'ordensservico.full'],
			'write' => ['ordensservico.update', 'ordensservico.full'],
		],
		'servicedesk' => [
			'view' => ['servicedesk.view', 'servicedesk.tickets'],
			'write' => ['servicedesk.update', 'servicedesk.tickets'],
		],
		'financeiro' => [
			'view' => ['financeiro.view'],
			'write' => ['financeiro.view'],
		],
		'bancos' => [
			'view' => ['financeiro.view', 'financeiro.bancos'],
			'write' => ['financeiro.bancos'],
		],
		'fornecedores' => [
			'view' => ['clientes.view', 'clientes.manage'],
			'write' => ['clientes.update', 'clientes.manage'],
		],
		'pcp' => [
			'view' => ['produtos.view', 'produtos.manage', 'ordensservico.list', 'ordensservico.full'],
			'write' => ['ordensservico.update', 'ordensservico.full'],
		],
		'empresas' => [
			'view' => ['empresas.view', 'empresas.manage'],
			'write' => ['empresas.update', 'empresas.manage'],
		],
		'sistema' => [
			'view' => ['config.manage', 'config.index'],
			'write' => ['config.manage'],
		],
		'licencas' => [
			'view' => ['licencas.view', 'licencas.manage'],
			'write' => ['licencas.manage'],
		],
	],
	// controller => action (minúsculo) => chave em modules (write|pricing)
	'write_actions' => [
		'ClientesPrototype' => [
			'apiatualizarcontato' => 'write',
		],
		'ProdutosPrototype' => [
			'apiatualizarcampo' => 'write',
			'precosave' => 'pricing',
		],
		'OrcamentosPrototype' => [
			'mudarstatus' => 'write',
			'apiatualizaritem' => 'write',
			'apiexcluiritem' => 'write',
			'apiadicionaritem' => 'write',
			'salvarrascunho' => 'write',
		],
		'OrdensservicoPrototype' => [
			'avancaretapa' => 'write',
			'apiatualizaritem' => 'write',
			'apiexcluiritem' => 'write',
			'apiadicionaritem' => 'write',
			'salvarrascunho' => 'write',
		],
		'ServicedeskPrototype' => [
			'aprovacao' => 'write',
		],
		'BancosPrototype' => [
			'rejeitarmatch' => 'write',
			'conciliar' => 'write',
			'salvarconta' => 'write',
		],
		'LicencasPrototype' => [
			'salvarwizard' => 'write',
			'salvarcatalogoproduto' => 'write',
			'salvarcategoria' => 'write',
			'salvardispositivo' => 'write',
			'salvarcofre' => 'write',
			'atualizarsolicitacao' => 'write',
			'salvarconfig' => 'write',
		],
	],
	// Chaves do menu (sidebar.ctp item key) → códigos OR (string ou array)
	'sidebar_item_gates' => [
		'dashboard' => 'dashboard.view',
		'clientes' => 'clientes.view',
		'produtos' => 'produtos.view',
		'estoque' => 'produtos.view',
		'precos' => 'produtos.pricing',
		'historico-precos' => 'produtos.view',
		'fornecedores' => 'clientes.view',
		'orc-lista' => 'orcamentos.view',
		'os-lista' => 'ordensservico.list',
		'os-kanban' => 'ordensservico.list',
		'sd' => ['servicedesk.view', 'servicedesk.tickets'],
		'sd-dashboard' => ['servicedesk.view', 'servicedesk.tickets'],
		'sd-fila' => ['servicedesk.view', 'servicedesk.tickets'],
		'sd-meus' => ['servicedesk.view', 'servicedesk.tickets'],
		'sd-grupo' => ['servicedesk.view', 'servicedesk.tickets'],
		'sd-kanban' => ['servicedesk.view', 'servicedesk.tickets'],
		'sd-aprovacoes' => ['servicedesk.view', 'servicedesk.tickets'],
		'sd-cmdb' => ['servicedesk.view', 'servicedesk.tickets'],
		'sd-problemas' => ['servicedesk.view', 'servicedesk.tickets'],
		'sd-mudancas' => ['servicedesk.view', 'servicedesk.tickets'],
		'sd-contratos' => ['servicedesk.view', 'servicedesk.tickets'],
		'sd-fat' => ['servicedesk.view', 'servicedesk.tickets'],
		'sd-kb' => ['servicedesk.view', 'servicedesk.tickets'],
		'sd-portal' => ['servicedesk.view', 'servicedesk.tickets'],
		'sd-calendar' => ['servicedesk.view', 'servicedesk.tickets'],
		'sd-csat' => ['servicedesk.view', 'servicedesk.tickets'],
		'sd-relatorios' => ['servicedesk.view', 'servicedesk.tickets'],
		'sd-config' => ['servicedesk.view', 'servicedesk.tickets'],
		'sd-perm' => ['servicedesk.view', 'servicedesk.tickets'],
		'sd-integracoes' => ['servicedesk.view', 'servicedesk.tickets'],
		'pcp' => ['produtos.view', 'ordensservico.list'],
		'pcp-dashboard' => ['produtos.view', 'ordensservico.list'],
		'engenharia' => ['produtos.view', 'ordensservico.list'],
		'bom' => ['produtos.view', 'ordensservico.list'],
		'roteiro' => ['produtos.view', 'ordensservico.list'],
		'mrp' => ['produtos.view', 'ordensservico.list'],
		'op-lista' => ['produtos.view', 'ordensservico.list'],
		'apontamento' => ['produtos.view', 'ordensservico.list'],
		'qualidade-ind' => ['produtos.view', 'ordensservico.list'],
		'expedicao' => ['produtos.view', 'ordensservico.list'],
		'financeiro' => 'financeiro.view',
		'orc-faturamento' => 'financeiro.view',
		'titulos' => 'financeiro.view',
		'cobranca' => 'financeiro.view',
		'contas-pagar' => 'financeiro.view',
		'nfe' => 'financeiro.view',
		'dre' => 'financeiro.view',
		'relatorios-fin' => 'financeiro.view',
		'bancos' => 'financeiro.view',
		'contas' => 'financeiro.view',
		'extrato' => 'financeiro.view',
		'conciliacao' => 'financeiro.view',
		'transferencias' => 'financeiro.view',
		'fluxo-caixa' => 'financeiro.view',
		'lic-dashboard' => ['licencas.view', 'licencas.manage'],
		'lic-empresas' => ['licencas.view', 'licencas.manage'],
		'lic-fornecedores' => ['licencas.view', 'licencas.manage'],
		'lic-licencas' => ['licencas.view', 'licencas.manage'],
		'lic-catalogo' => ['licencas.view', 'licencas.manage'],
		'lic-cofre' => ['licencas.cofre.view', 'licencas.manage'],
		'lic-renovacoes' => ['licencas.view', 'licencas.manage'],
		'lic-solicitacoes' => ['licencas.view', 'licencas.manage'],
		'lic-auditoria' => ['licencas.manage'],
		'lic-config' => ['licencas.manage'],
		'lic-inteligencia' => ['licencas.view', 'licencas.manage'],
		'lic-relatorios' => ['licencas.view', 'licencas.manage'],
	],
];
